controller_list:
  - name: thumb_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - thumb_joint_1
      - thumb_joint_2
      - thumb_joint_3
  - name: index_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - index_joint_1
      - index_joint_2
      - index_joint_3
  - name: middle_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - middle_joint_1
      - middle_joint_2
      - middle_joint_3
  - name: ring_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - ring_joint_1
      - ring_joint_2
      - ring_joint_3
  - name: little_group_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - little_joint_1
      - little_joint_2
      - little_joint_3