hand:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
   # Position Controllers ---------------------------------------
  thumb_joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: thumb_joint_1
    pid: {p: 0.05, i: 0.01, d: 0.0}
  thumb_joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: thumb_joint_2
    pid: {p: 0.05, i: 0.01, d: 0.0}
  thumb_joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: thumb_joint_3
    pid: {p: 0.05, i: 0.01, d: 0.0}
  index_joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: index_joint_1
    pid: {p: 0.05, i: 0.01, d: 0.0}
  index_joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: index_joint_2
    pid: {p: 0.05, i: 0.01, d: 0.0}
  index_joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: index_joint_3
    pid: {p: 0.05, i: 0.01, d: 0.0}
  middle_joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: middle_joint_1
    pid: {p: 0.05, i: 0.01, d: 0.0}
  middle_joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: middle_joint_2
    pid: {p: 0.05, i: 0.01, d: 0.0}
  middle_joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: middle_joint_3
    pid: {p: 0.05, i: 0.01, d: 0.0}
  ring_joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: ring_joint_1
    pid: {p: 0.05, i: 0.01, d: 0.0}
  ring_joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: ring_joint_2
    pid: {p: 0.05, i: 0.01, d: 0.0}
  ring_joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: ring_joint_3
    pid: {p: 0.05, i: 0.01, d: 0.0}
  little_joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: little_joint_1
    pid: {p: 0.05, i: 0.01, d: 0.0}
  little_joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: little_joint_2
    pid: {p: 0.05, i: 0.01, d: 0.0}
  little_joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: little_joint_3
    pid: {p: 0.05, i: 0.01, d: 0.0}
