thumb_joint_1_controller:
  type: effort_controllers/JointPositionController
  joint: thumb_joint_1
  pid: {p: 0.05, i: 0.01, d: 0.0}
thumb_joint_2_controller:
  type: effort_controllers/JointPositionController
  joint: thumb_joint_2
  pid: {p: 0.05, i: 0.01, d: 0.0}
thumb_joint_3_controller:
  type: effort_controllers/JointPositionController
  joint: thumb_joint_3
  pid: {p: 0.05, i: 0.01, d: 0.0}