exoskelaton:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
   # Position Controllers ---------------------------------------
  joint_1_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10, i: 3.0, d: 0.2}
  joint_2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10, i: 3.0, d: 0.2}
  joint_3_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 10, i: 3.0, d: 0.2}
  joint_4_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 10, i: 3.0, d: 0.2}
  joint_5_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10, i: 3.0, d: 0.2}
